CREATE TYPE "public"."provider_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "status" "provider_status" DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "category" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "reason_for_listing" text;--> statement-breakpoint
ALTER TABLE "providers" ADD CONSTRAINT "providers_user_id_unique" UNIQUE("user_id");--> statement-breakpoint
-- Hand-added backfill; everything above was generated by drizzle-kit.
--
-- Adding "status" with DEFAULT 'pending' marked every existing row pending.
-- None of them is an application awaiting review: each is either the
-- first-party provider (user_id NULL, lists the eight approved products) or a
-- user who signed up as a provider under the old flow, which granted the role
-- on the spot. They were providers before this migration and stay providers.
--
-- Updating every row is correct only because it runs here, in the same
-- migration that created the column — no application can have been written
-- yet. Never copy this statement into a later migration.
UPDATE "providers" SET "status" = 'approved';