ALTER TABLE "products" ADD COLUMN "rejection_reason" text;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "submitted_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "reviewed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "rejection_reason" text;--> statement-breakpoint
-- Hand-added backfill; everything above was generated by drizzle-kit.
--
-- "submitted_at" was added with DEFAULT now(), which stamped every existing
-- row with the moment this migration ran. For a pending application that is
-- wrong — it would sort the queue by migration time. "created_at" is when the
-- row was first written, which for anything created before this column
-- existed is the best record there is of when it was submitted (a
-- resubmission time was never stored).
--
-- Updating every row is correct only because it runs in the migration that
-- creates the column. Never copy this statement into a later migration.
UPDATE "providers" SET "submitted_at" = "created_at";
